[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
solana_rfq_v2 = "RFQ27dg5gSha2cDzQxuGyhfkz5CK2fUSy3Sjw4Rptyj"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[test.validator]
rpc_port = 18899
faucet_port = 19900

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
